### ISSUE TITLE
Is there a way to override the `--intialise-insecure` setting?

### ISSUE THREAD

**Issue by DaveParr** [ClearcodeHQ/pytest-mysql#180]
In my conftest.py I have the following:

```python
from pytest_mysql import factories

mysql_proc = factories.mysql_proc(mysqld_exec="/Applications/MAMP/Library/bin/mysql")
```

This is deliberately executing against the MAMP installation of mysql (as that is currently the only install I have on this machine)

I have this test (taken from this repos own tests):
```python
def test_proc(mysql_proc):
    """Check first, basic server fixture factory."""
    assert mysql_proc.running()
```
Which fails with:
```
---------------------------- Captured stderr setup -----------------------------
mysql: [ERROR] unknown option '--initialize-insecure'
```

I believe it is arising from this line here:
https://github.com/ClearcodeHQ/pytest-mysql/blob/2414ea96bfb64cb191224ca83dd636894012fbb9/src/pytest_mysql/executor.py#L122

What is the reasoning behind this argument from the pytest-mysql view (I expect you have one, I just don't know what this option does :) )? 
Is directing the module to hit the MAMP installation supported, either explictly or implicitly?
Is there a way I can overcome this error, either from the python side, or the MAMP installation side?

**Comment by fizyk** [comment]
First of all `--initialize-insecure` and `--initialize` is mysqld option, not mysql executable. You need to change the command reference to point to that.

Both of these options are used to initialize database, the latter is used to do it without the root password.
More: https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization.html

MySQL has it's own set of users, and otherwise we'd need to have also a password parameter.

**Comment by DaveParr** [comment]
Thanks @fizyk, my mistake. For my the correct path is:
```
mysql_proc = factories.mysql_proc(
    mysqld_exec="/Applications/MAMP/Library/bin/mysqld",
    mysqld_safe="/Applications/MAMP/Library/bin/mysqld_safe")
```

I am having a different issue now, but in this specific case of `--initialise_insecure`, the issue seems corrected.

Current output errors about yeilding to mysql_proc, but I will work on that separately:
```
        mysql_executor = MySQLExecutor(
            mysqld_safe=mysql_mysqld_safe,
            mysqld=mysql_mysqld,
            admin_exec=mysql_admin_exec,
            logfile_path=logfile_path,
            base_directory=tmpdir,
            params=mysql_params,
            user=config['user'],
            host=mysql_host,
            port=mysql_port,
            install_db=mysql_install_db
        )
        with mysql_executor:
>           yield mysql_executor

../../../.virtualenvs/data-science-api/lib/python3.7/site-packages/pytest_mysql/factories/process.py:118: 
```

Thanks for the pointer.
