### ISSUE TITLE
Is it possible to execute test on a already running mysql service?

### ISSUE THREAD

**Issue by lioramilbaum** [ClearcodeHQ/pytest-mysql#214]
The mysql service is spined by vagrant in a guest machine with a configured port forwarding
There is no need for spinning a mysql service on the host machine.

**Comment by fizyk** [comment]
not at the moment

Although the solution is basically ready, one would have to just copy/adjust solution prepare ie in here:
https://github.com/ClearcodeHQ/pytest-postgresql/pull/247

**Comment by lioramilbaum** [comment]
Thank @fizyk. I have moved forward and implemented a fixture which addresses my use case.
