### ISSUE TITLE
Trying to replicate example tests

### ISSUE THREAD

**Issue by ggdhines** [ClearcodeHQ/pytest-mysql#231]
I'm trying to follow the example test code in this [repo](https://github.com/ClearcodeHQ/pytest-mysql/tree/master/tests). I have mysql installed on OS 10.15.4 via Homebrew. My conftest.py file looks like
```
from pytest_mysql import factories

mysql_proc = factories.mysql_proc()
mysql = factories.mysql('mysql_proc')
```

and my test_example.py file looks like
```
def test_first_test(mysql_proc):
    assert mysql_proc.running()
```
finally my pytest.ini file
```
[pytest]
mysql_mysqld_safe = /usr/local/bin/mysqld_safe
mysql_admin = /usr/local/bin/mysqladmin
mysql_passwd = **
port = 3306
```

When I run pytest. I get the error 
```
subprocess.CalledProcessError: Command '/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-15/pytest-mysql0/mysql.22888.sock --user=root shutdown' returned non-zero exit status 1.

I've looked around and have no idea what's going on. Anything would be greatly appreciated. Thanks :)
```

**Comment by fizyk** [comment]
@ggdhines 
```
from pytest_mysql import factories

mysql_proc = factories.mysql_proc()
mysql = factories.mysql('mysql_proc')
```

if you don't change anything, that's not needed.

Could you post the full test ouptut? that command is being run at the end of the tests, so test run fine, but there seems to be an issue closing it all...

**Comment by ggdhines** [comment]
Sorry for the delayed response - complete output is
---
Testing started at 11:54 AM ...
/Users/greg/opt/anaconda3/envs/bluedot/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_pytest_runner.py" --path /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests/test_iata_access.py
Launching pytest with arguments /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests/test_iata_access.py in /Users/greg/PycharmProjects/flight_simulator

============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests, inifile: pytest.ini
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, mysql-2.0.1, remotedata-0.3.1, hypothesis-5.5.1, astropy-header-0.1.2collected 1 item

flight_simulator/tests/test_iata_access.py .Emysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql' (2)'
Check that mysqld is running and that the socket: '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock' exists!

test_iata_access.py:3 (test_first_test)
request = <SubRequest 'mysql_proc' for <Function test_first_test>>
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x119bfe510>, _basetemp=PosixPath('/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0')))

    @pytest.fixture(scope='session')
    def mysql_proc_fixture(request, tmpdir_factory):
        """
        Process fixture for MySQL server.
    
        #. Get config.
        #. Initialize MySQL data directory
        #. `Start a mysqld server
            <https://dev.mysql.com/doc/refman/5.0/en/mysqld-safe.html>`_
        #. Stop server and remove directory after tests.
            `See <https://dev.mysql.com/doc/refman/5.6/en/mysqladmin.html>`_
    
        :param FixtureRequest request: fixture request object
        :param tmpdir_factory: pytest fixture for temporary directories
        :rtype: pytest_dbfixtures.executors.TCPExecutor
        :returns: tcp executor
    
        """
        config = get_config(request)
        mysql_mysqld = mysqld_exec or config['mysqld']
        mysql_admin_exec = admin_executable or config['admin']
        mysql_mysqld_safe = mysqld_safe or config['mysqld_safe']
        mysql_port = get_port(port) or get_port(config['port'])
        mysql_host = host or config['host']
        mysql_params = params or config['params']
        mysql_install_db = install_db or config['install_db']
    
        tmpdir = tmpdir_factory.mktemp('pytest-mysql')
    
        logsdir = config['logsdir']
        logfile_path = os.path.join(
            logsdir,
            '{prefix}mysql-server.{port}.log'.format(
                prefix=logs_prefix,
                port=mysql_port
            )
        )
    
        mysql_executor = MySQLExecutor(
            mysqld_safe=mysql_mysqld_safe,
            mysqld=mysql_mysqld,
            admin_exec=mysql_admin_exec,
            logfile_path=logfile_path,
            base_directory=tmpdir,
            params=mysql_params,
            user=config['user'],
            host=mysql_host,
            port=mysql_port,
            install_db=mysql_install_db
        )
        with mysql_executor:
>           yield mysql_executor

../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/factories/process.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/mirakuru/base.py:179: in __exit__
    self.stop()
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/executor.py:191: in stop
    self.shutdown()
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/executor.py:187: in shutdown
    subprocess.check_output(shutdown_command, shell=True)
../../opt/anaconda3/envs/bluedot/lib/python3.7/subprocess.py:411: in check_output
    **kwargs).stdout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = ('/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown',)
kwargs = {'shell': True, 'stdout': -1}
process = <subprocess.Popen object at 0x119c19690>, stdout = b'', stderr = None
retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
                raise CalledProcessError(retcode, process.args,
>                                        output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown' returned non-zero exit status 1.

../../opt/anaconda3/envs/bluedot/lib/python3.7/subprocess.py:512: CalledProcessError
                            [100%]

==================================== ERRORS ====================================
_____________________ ERROR at teardown of test_first_test _____________________

request = <SubRequest 'mysql_proc' for <Function test_first_test>>
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x119bfe510>, _basetemp=PosixPath('/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0')))

    @pytest.fixture(scope='session')
    def mysql_proc_fixture(request, tmpdir_factory):
        """
        Process fixture for MySQL server.
    
        #. Get config.
        #. Initialize MySQL data directory
        #. `Start a mysqld server
            <https://dev.mysql.com/doc/refman/5.0/en/mysqld-safe.html>`_
        #. Stop server and remove directory after tests.
            `See <https://dev.mysql.com/doc/refman/5.6/en/mysqladmin.html>`_
    
        :param FixtureRequest request: fixture request object
        :param tmpdir_factory: pytest fixture for temporary directories
        :rtype: pytest_dbfixtures.executors.TCPExecutor
        :returns: tcp executor
    
        """
        config = get_config(request)
        mysql_mysqld = mysqld_exec or config['mysqld']
        mysql_admin_exec = admin_executable or config['admin']
        mysql_mysqld_safe = mysqld_safe or config['mysqld_safe']
        mysql_port = get_port(port) or get_port(config['port'])
        mysql_host = host or config['host']
        mysql_params = params or config['params']
        mysql_install_db = install_db or config['install_db']
    
        tmpdir = tmpdir_factory.mktemp('pytest-mysql')
    
        logsdir = config['logsdir']
        logfile_path = os.path.join(
            logsdir,
            '{prefix}mysql-server.{port}.log'.format(
                prefix=logs_prefix,
                port=mysql_port
            )
        )
    
        mysql_executor = MySQLExecutor(
            mysqld_safe=mysql_mysqld_safe,
            mysqld=mysql_mysqld,
            admin_exec=mysql_admin_exec,
            logfile_path=logfile_path,
            base_directory=tmpdir,
            params=mysql_params,
            user=config['user'],
            host=mysql_host,
            port=mysql_port,
            install_db=mysql_install_db
        )
        with mysql_executor:
>           yield mysql_executor

../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/factories/process.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/mirakuru/base.py:179: in __exit__
    self.stop()
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/executor.py:191: in stop
    self.shutdown()
../../opt/anaconda3/envs/bluedot/lib/python3.7/site-packages/pytest_mysql/executor.py:187: in shutdown
    subprocess.check_output(shutdown_command, shell=True)
../../opt/anaconda3/envs/bluedot/lib/python3.7/subprocess.py:411: in check_output
    **kwargs).stdout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = ('/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown',)
kwargs = {'shell': True, 'stdout': -1}
process = <subprocess.Popen object at 0x119c19690>, stdout = b'', stderr = None
retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
                raise CalledProcessError(retcode, process.args,
>                                        output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown' returned non-zero exit status 1.

../../opt/anaconda3/envs/bluedot/lib/python3.7/subprocess.py:512: CalledProcessError
--------------------------- Captured stderr teardown ---------------------------
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql' (2)'
Check that mysqld is running and that the socket: '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock' exists!
====================== 1 passed, 1 error in 4.20 seconds =======================
Process finished with exit code 0

**Comment by ggdhines** [comment]
Sorry for the delayed response. Complete output is 
---
Testing started at 11:54 AM ...
/Users/greg/opt/anaconda3/envs/my_env/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_pytest_runner.py" --path /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests/test_iata_access.py
Launching pytest with arguments /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests/test_iata_access.py in /Users/greg/PycharmProjects/flight_simulator

============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /Users/greg/PycharmProjects/flight_simulator/flight_simulator/tests, inifile: pytest.ini
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, mysql-2.0.1, remotedata-0.3.1, hypothesis-5.5.1, astropy-header-0.1.2collected 1 item

flight_simulator/tests/test_iata_access.py .Emysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql' (2)'
Check that mysqld is running and that the socket: '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock' exists!

test_iata_access.py:3 (test_first_test)
request = <SubRequest 'mysql_proc' for <Function test_first_test>>
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x119bfe510>, _basetemp=PosixPath('/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0')))

    @pytest.fixture(scope='session')
    def mysql_proc_fixture(request, tmpdir_factory):
        """
        Process fixture for MySQL server.
    
        #. Get config.
        #. Initialize MySQL data directory
        #. `Start a mysqld server
            <https://dev.mysql.com/doc/refman/5.0/en/mysqld-safe.html>`_
        #. Stop server and remove directory after tests.
            `See <https://dev.mysql.com/doc/refman/5.6/en/mysqladmin.html>`_
    
        :param FixtureRequest request: fixture request object
        :param tmpdir_factory: pytest fixture for temporary directories
        :rtype: pytest_dbfixtures.executors.TCPExecutor
        :returns: tcp executor
    
        """
        config = get_config(request)
        mysql_mysqld = mysqld_exec or config['mysqld']
        mysql_admin_exec = admin_executable or config['admin']
        mysql_mysqld_safe = mysqld_safe or config['mysqld_safe']
        mysql_port = get_port(port) or get_port(config['port'])
        mysql_host = host or config['host']
        mysql_params = params or config['params']
        mysql_install_db = install_db or config['install_db']
    
        tmpdir = tmpdir_factory.mktemp('pytest-mysql')
    
        logsdir = config['logsdir']
        logfile_path = os.path.join(
            logsdir,
            '{prefix}mysql-server.{port}.log'.format(
                prefix=logs_prefix,
                port=mysql_port
            )
        )
    
        mysql_executor = MySQLExecutor(
            mysqld_safe=mysql_mysqld_safe,
            mysqld=mysql_mysqld,
            admin_exec=mysql_admin_exec,
            logfile_path=logfile_path,
            base_directory=tmpdir,
            params=mysql_params,
            user=config['user'],
            host=mysql_host,
            port=mysql_port,
            install_db=mysql_install_db
        )
        with mysql_executor:
>           yield mysql_executor

../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/factories/process.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/mirakuru/base.py:179: in __exit__
    self.stop()
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/executor.py:191: in stop
    self.shutdown()
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/executor.py:187: in shutdown
    subprocess.check_output(shutdown_command, shell=True)
../../opt/anaconda3/envs/my_env/lib/python3.7/subprocess.py:411: in check_output
    **kwargs).stdout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = ('/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown',)
kwargs = {'shell': True, 'stdout': -1}
process = <subprocess.Popen object at 0x119c19690>, stdout = b'', stderr = None
retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
                raise CalledProcessError(retcode, process.args,
>                                        output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown' returned non-zero exit status 1.

../../opt/anaconda3/envs/my_env/lib/python3.7/subprocess.py:512: CalledProcessError
                            [100%]

==================================== ERRORS ====================================
_____________________ ERROR at teardown of test_first_test _____________________

request = <SubRequest 'mysql_proc' for <Function test_first_test>>
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x119bfe510>, _basetemp=PosixPath('/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0')))

    @pytest.fixture(scope='session')
    def mysql_proc_fixture(request, tmpdir_factory):
        """
        Process fixture for MySQL server.
    
        #. Get config.
        #. Initialize MySQL data directory
        #. `Start a mysqld server
            <https://dev.mysql.com/doc/refman/5.0/en/mysqld-safe.html>`_
        #. Stop server and remove directory after tests.
            `See <https://dev.mysql.com/doc/refman/5.6/en/mysqladmin.html>`_
    
        :param FixtureRequest request: fixture request object
        :param tmpdir_factory: pytest fixture for temporary directories
        :rtype: pytest_dbfixtures.executors.TCPExecutor
        :returns: tcp executor
    
        """
        config = get_config(request)
        mysql_mysqld = mysqld_exec or config['mysqld']
        mysql_admin_exec = admin_executable or config['admin']
        mysql_mysqld_safe = mysqld_safe or config['mysqld_safe']
        mysql_port = get_port(port) or get_port(config['port'])
        mysql_host = host or config['host']
        mysql_params = params or config['params']
        mysql_install_db = install_db or config['install_db']
    
        tmpdir = tmpdir_factory.mktemp('pytest-mysql')
    
        logsdir = config['logsdir']
        logfile_path = os.path.join(
            logsdir,
            '{prefix}mysql-server.{port}.log'.format(
                prefix=logs_prefix,
                port=mysql_port
            )
        )
    
        mysql_executor = MySQLExecutor(
            mysqld_safe=mysql_mysqld_safe,
            mysqld=mysql_mysqld,
            admin_exec=mysql_admin_exec,
            logfile_path=logfile_path,
            base_directory=tmpdir,
            params=mysql_params,
            user=config['user'],
            host=mysql_host,
            port=mysql_port,
            install_db=mysql_install_db
        )
        with mysql_executor:
>           yield mysql_executor

../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/factories/process.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/mirakuru/base.py:179: in __exit__
    self.stop()
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/executor.py:191: in stop
    self.shutdown()
../../opt/anaconda3/envs/my_env/lib/python3.7/site-packages/pytest_mysql/executor.py:187: in shutdown
    subprocess.check_output(shutdown_command, shell=True)
../../opt/anaconda3/envs/my_env/lib/python3.7/subprocess.py:411: in check_output
    **kwargs).stdout
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = ('/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown',)
kwargs = {'shell': True, 'stdout': -1}
process = <subprocess.Popen object at 0x119c19690>, stdout = b'', stderr = None
retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
                raise CalledProcessError(retcode, process.args,
>                                        output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '/usr/local/bin/mysqladmin --socket=/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock --user=root shutdown' returned non-zero exit status 1.

../../opt/anaconda3/envs/my_env/lib/python3.7/subprocess.py:512: CalledProcessError
--------------------------- Captured stderr teardown ---------------------------
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql' (2)'
Check that mysqld is running and that the socket: '/private/var/folders/bx/s17rfknj0950lvd648ptdrcr0000gn/T/pytest-of-greg/pytest-0/pytest-mysql0/mysql.42698.sock' exists!
====================== 1 passed, 1 error in 4.20 seconds =======================
Process finished with exit code 0

**Comment by fizyk** [comment]
Hmmm... what system are you using?
Somehow the socket is not there where it should be, and Can't figure why :thinking:

**Comment by fizyk** [comment]
Duplicate #183
