### ISSUE TITLE
Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by ravi2k16** [ClearcodeHQ/pytest-mysql#240]
simply ran following code on my ubuntu-20 machine running with mysql server bug got below error
(python version 3.8.2)
-----------------------------------------------------
def test_using_postgresql(mysql_proc, mysql):
    mysql.query("SELECT version();")
-----------------------------------------------------

(common-venv-3.8.2) /home/ravi/cprog/for-mysql>pytest 
======================================================================================= test session starts ========================================================================================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/ravi/cprog/for-mysql
plugins: mysql-2.0.1, flask-1.0.0, postgresql-2.4.0
collected 1 item                                                                                                                                                                                   

test_w.py .E                                                                                                                                                                                 [100%]

============================================================================================== ERRORS ==============================================================================================
____________________________________________________________________________ ERROR at teardown of test_using_postgresql ____________________________________________________________________________

    def drop_database():
>       mysql_conn.query('DROP DATABASE IF EXISTS %s' % mysql_db)

../../.pyenv/versions/3.8.2/envs/common-venv-3.8.2/lib/python3.8/site-packages/pytest_mysql/factories/client.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_mysql.connection open to 'localhost' at 0x55df362acf20>, query = 'DROP DATABASE IF EXISTS test'

    def query(self, query):
        # Since _mysql releases GIL while querying, we need immutable buffer.
        if isinstance(query, bytearray):
            query = bytes(query)
>       _mysql.connection.query(self, query)
E       MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

../../.pyenv/versions/3.8.2/envs/common-venv-3.8.2/lib/python3.8/site-packages/MySQLdb/connections.py:259: ProgrammingError
===================================================================================== short test summary info ======================================================================================
ERROR test_w.py::test_using_postgresql - MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
=================================================================================== 1 passed, 1 error in 17.84s ===================================================================

**Comment by fizyk** [comment]
I'm a bit confused, as it states test_postgresql.

Anyway, you haven't fetched your select version results, which caused the error for you.

**Comment by ravi2k16** [comment]
>>>> I'm a bit confused, as it states test_postgresql.

Sorry by mistake I put wrong function name.  it should be   test_mysql

>>>> Anyway, you haven't fetched your select version results, which caused the error for you.

Could not understand this part as I am new to pytest and pytest-mysql.   
what should be full code for this function to work?  how to fetch version result.

this is how it is shown as example in  source code's  tests/test_mysql.py

def test_mysql_test_without_cursor(mysql):
    """Run test without cursor and without fetching the data."""
    mysql.query("SELECT VERSION();")



-/thanks

**Comment by fizyk** [comment]
@ravi2k16 the issue you're encountering is not related to pytest nor pytest-mysql specifically, but rather to mysql.

In all databases, when you query with select the database, you need to fetch the data. Some tools are fetching results automatically, some not.

your query selects version, and in order for it to work, you need to fetch the data.

Look here, although I'm not fetching the data itself, rather performing action on the data itself:
https://github.com/ClearcodeHQ/pytest-mysql/blob/master/tests/test_mysql.py#L13

You'd need to use fetchone, fetchall or fetchmany on the cursor to fetch the data here.

**Comment by ravi2k16** [comment]
> @ravi2k16 the issue you're encountering is not related to pytest nor pytest-mysql specifically, but rather to mysql.
> 
> In all databases, when you query with select the database, you need to fetch the data. Some tools are fetching results automatically, some not.
> 
> your query selects version, and in order for it to work, you need to fetch the data.
> 
> Look here, although I'm not fetching the data itself, rather performing action on the data itself:
> https://github.com/ClearcodeHQ/pytest-mysql/blob/master/tests/test_mysql.py#L13
> 
> You'd need to use fetchone, fetchall or fetchmany on the cursor to fetch the data here.

i am simply testing the sample code given in tests dir (tests/test_mysql.py). does it mean that is wrong ? i see you are also not fetching any data in that function.

def test_mysql_test_without_cursor(mysql):
    """Run test without cursor and without fetching the data."""
    mysql.query("SELECT VERSION();")

-/Thanks

**Comment by fizyk** [comment]
You mean the test from the pull request related to your issue? I'm changing the code to be more forgiven. If you'll look more closely, I also change the client fixture, to actually fetch the data just in case. Check the other tests, especially the one I linked.

And in other tests, I haven't fetched data, because I haven't queried (select query) for it.

**Comment by ravi2k16** [comment]
>>>> You mean the test from the pull request related to your issue? 
yes. I simply pulled your entire pytest-mysql code and run  pytest in  test_mysql.py
and it gave me that error.

>>>> If you'll look more closely, I also change the client fixture, to actually fetch the data just in case.
which file and which line are you referring?  if this is the case then git code should not give any problem. 
Am i doing something wrong here ?

>>> And in other tests, I haven't fetched data, because I haven't queried (select query) for it.
i am only talking for select query. Others I have commented out so no question on that.

I would be grateful to you if you help me resolving that issue. As I am new to pytest, I might be doing some
silly mistakes while using this library but what...

Thanks

**Comment by fizyk** [comment]
Please update pytest-mysql to the newest version. You ought to be safe. As for querying and fetching, that'd actually have to be checked against mysql and mysqlclient itself

**Comment by fizyk** [comment]
Maybe read this documentation: https://mysqlclient.readthedocs.io/user_guide.html?highlight=use_result#some-mysql-examples

**Comment by ravi2k16** [comment]
> Maybe read this documentation: https://mysqlclient.readthedocs.io/user_guide.html?highlight=use_result#some-mysql-examples


thanks fizyk for updating the code. however i still face below issue in connecting to mysql using the sample code.
I am able to connect to mysql using  cli tool   "mysql -h localhost  -u root -p"   hence i do not think any issue with
root@localhost    then why i am getting this error?  i understand this issue might not be related to pytest, however
if you help reg mysql connectivity, i would highly appreciate. pytest.ini and trace log has already been shared previously.



E       MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

../../.pyenv/versions/common-venv-3.8.2/lib/python3.8/site-packages/MySQLdb/connections.py:185: OperationalError
_________________________________________________________________________ ERROR at setup of test_mysql_test_without_cursor _________________________________________________________________________


-/Thanks
