### ISSUE TITLE
Access denied for user 'root'@'localhost

### ISSUE THREAD

**Issue by ravi2k16** [ClearcodeHQ/pytest-mysql#242]
### What action do you want to perform
trying to run available test example 

cat tests/test_mysql.py
-------------------------
def test_mysql_test_without_cursor(mysql):
    """Run test without cursor and without fetching the data."""
    mysql.query("SELECT VERSION();")

cat    pytest.ini
-------------------------------------------------------------
[pytest]
mysql_dbname = testdb
xfail_strict = true
mysql_host = localhost
mysql_port = 33061
mysql_user = root
mysql_passwd = root
 

### What are the results
received 

E       MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

--- tried to fix by running below in mysql  but did not help

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
FLUSH PRIVILEGES;

--- able to login as user: root pass:root on cmd line             mysql -u root -p

### What are the expected results
test should be successful.

**Comment by fizyk** [comment]
please post full stacktrace. And I'd appreciate also a test code

**Comment by fizyk** [comment]
You might have to read a bit more: https://dev.mysql.com/doc/refman/5.6/en/error-lost-connection.html

Mind that the mysql isntance set up by pytest-mysql is completely new instance, not related to the one running by default in your system.

Which test passes (use -v paramter to pytest)? Could you run each test separately? using -k 'testname' parameter?

**Comment by ravi2k16** [comment]
> You might have to read a bit more: https://dev.mysql.com/doc/refman/5.6/en/error-lost-connection.html
> 
> Mind that the mysql isntance set up by pytest-mysql is completely new instance, not related to the one running by default in your system.
> 
> Which test passes (use -v paramter to pytest)? Could you run each test separately? using -k 'testname' parameter?



thanks Grzegorz. I am able to resolve the issue now.however I have a suggestion here, we should have a db table assert feature also as we have variable assert in pytest (assert i == 4)
TableAssert tbl = { table_content.....}
Do we have any such thing ?

**Comment by fizyk** [comment]
I don't think I understand, what you mean.

**Comment by ravi2k16** [comment]
we use assert operator to compare the current variable value and expected
variable value. if not matches then it fails.

the same way is there a table assert operation which compares the actual
table content with the expected contents.
table assert operation should have features of comparing based on the give
cell/rows/columns values etc

**Comment by fizyk** [comment]
no, you'll need to fetch the data to the list of dictionaries and prepare list of dictionaries with expected values (and order) yourself

**Comment by ravi2k16** [comment]
thanks Grzegorz for your help and support.

**Comment by fizyk** [comment]
it'll help if you'd use sets instead of lists. then you'd have to keep track of their order if that's not important.
