### ISSUE TITLE
Extend readme with examples

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [ClearcodeHQ/pytest-mysql#288]
I cannot see any usage docs, where are they?

**Comment by fizyk** [comment]
in readme, I don't think there's much more to write than the official pytest documentation provides.

**Comment by Abdur-rahmaanJ** [comment]
Well, for you it's super simple. But like even a demo usage in README helps. From your perspective it's super easy to connect the docs, but it is not so. I know you have tons of plugins to maintain but at least some README bits

**Comment by fizyk** [comment]
@Abdur-rahmaanJ Do I understand correctly, that you'd like to see some examples in README? Something like here: 
https://github.com/ClearcodeHQ/pytest-postgresql#examples ?

If so, I'll try to put something up (not sure when), in the meantime, have you seen the tests for this package?

**Comment by Abdur-rahmaanJ** [comment]
@fizyk yes like that, even for raw sql etc. But i guess a single page of docs somewhere with some opening remarks about different dbs might make more sense than many readmes. But yes much appreciated

**Comment by fizyk** [comment]
Okay, in the meantime take a look at tests: https://github.com/ClearcodeHQ/pytest-mysql/tree/master/tests 

I'm really not sure when I'll be able to sit on this package. But the issue stands.

**Comment by GabrieleCalarota** [comment]
I think more example of usage for pymysql and MySQL in general and usecase scenario would help. Trying to set this up is a real hassle. 
It's been almost a week I've been trying to set this up on localhost with already an instance of mysqld up&running but I can't make it work (I've copied all the test files in the source code exactly as they are and they fail to run)

**Comment by fizyk** [comment]
@GabrieleCalarota not sure what you're trying to do? Replace mysqlclient with pymysql in fixtures? Or you've got test running pymysql and and want to use that to also connect to the database from within your code?

**Comment by GabrieleCalarota** [comment]
> @GabrieleCalarota not sure what you're trying to do? Replace mysqlclient with pymysql in fixtures? Or you've got test running pymysql and and want to use that to also connect to the database from within your code?

Use Case is:
 - Python Code running query with pymysql connection
 - Connection is connecting to a localhost mysql database for user testing and demo purpose (but also in PROD)
 - I would like to use pytest to have codecoverage also of code blocks running a mysql query (with pymysql connector)
 - Those tests should work both locally (with a mysqld process up&running) and on github actions
 
 I somehow managed to make it work, but I'm still figuring it out. If this is a common scenario for people, I would suggest to put this into the readme so people don't have to figure it out by themselves
