### ISSUE TITLE
[ERROR] [TEARDOWN]: Connection already closed - mysql_conn.store_result() - MySQLdb._exceptions.OperationalError: (2006, '')

### ISSUE THREAD

**Issue by GabrieleCalarota** [ClearcodeHQ/pytest-mysql#340]
### What action do you want to perform
I would like to test with pytest-mysql a function that connects to the mysqldb (patched/mocked) and closes the connection in the function.

### What are the results
Testing with pytest-mysql I get this exception that turns out into 2 unexpected-behaviour:
```
request = <SubRequest 'mysqlnoproc_client' for <Function test_userExists_dummy_with_old_connect>>

    @pytest.fixture
    def mysql_fixture(request: FixtureRequest) -> MySQLdb.Connection:
        """
        Client fixture for MySQL server.
    
        #. Get config.
        #. Try to import MySQLdb package.
        #. Connect to mysql server.
        #. Create database.
        #. Use proper database.
        #. Drop database after tests.
    
        :param request: fixture request object
    
        :returns: connection to database
        """
        config = get_config(request)
        process: Union[
            NoopMySQLExecutor, MySQLExecutor
        ] = request.getfixturevalue(process_fixture_name)
        if not process.running():
            process.start()
    
        mysql_user = process.user
        mysql_passwd = passwd or config["passwd"]
        mysql_db = dbname or config["dbname"]
    
        connection_kwargs = {
            "host": process.host,
            "user": mysql_user,
            "passwd": mysql_passwd,
        }
        if process.unixsocket:
            connection_kwargs["unix_socket"] = process.unixsocket
        else:
            connection_kwargs["port"] = process.port
    
        query_str = (
            f"CREATE DATABASE {mysql_db} "
            f"DEFAULT CHARACTER SET {charset} "
            f"DEFAULT COLLATE {collation}"
        )
        try:
            mysql_conn: MySQLdb.Connection = _connect(
                connection_kwargs, query_str
            )
        except OperationalError:
            # Fallback to mysql connection with root user
            connection_kwargs["user"] = "root"
            mysql_conn: MySQLdb.Connection = _connect(
                connection_kwargs, query_str
            )
        mysql_conn.query(f"USE {mysql_db}")
        yield mysql_conn
    
        # clean up after test that forgot to fetch selected data
>       mysql_conn.store_result()
E       MySQLdb._exceptions.OperationalError: (2006, '')

../../../venv/lib/python3.8/site-packages/pytest_mysql/factories/client.py:134: OperationalError
```
So --> mysql_conn.store_result() is not closed in a try/except block and so --> function test gets all right but test fails with the exception raised.
Also this is not good with a connection mysql_noproc because database doesn't get DROPPED and we need to go into the console and drop it manually

### What are the expected results
 - [x] Try/except block surrounding mysql_conn.store_result()
 - [x] Database dropped anyway
 - [x] If connection is closed at mysql_conn.store_result() --> do nothing

If this makes sense to some people, I'll try propose a PR with these changes

**Comment by fizyk** [comment]
Okay, solution to this would be to actually try...except and catch the issue and then... reconnect to drop the database.

**Comment by fizyk** [comment]
Question, are you using this fixture connection to pass it to your tested code?

**Comment by GabrieleCalarota** [comment]
> Okay, solution to this would be to actually try...except and catch the issue and then... reconnect to drop the database.

Yes exactly, I've already implemented this in a branch I can eventually submit the PR if this makes sense to you.



> Question, are you using this fixture connection to pass it to your tested code?

I do something like this:

```python3
...
mysql_noproc2 = factories.mysql_noproc()
mysqlnoproc_client = factories.mysql("mysql_noproc2")

def get_create_database():
    return """CREATE TABLE ...."""

@pytest.fixture
def setup_db(mysqlnoproc_client):
    """Check if noproc fixture connects to the running mysql instance."""
    cursor = mysqlnoproc_client.cursor()
    query = get_create_database()
    cursor.execute(query)
    cursor.close()
    yield mysqlnoproc_client


@pytest.fixture
def patch_cursor(setup_db):
    import MySQLdb
    import pymysql
    pymysql.cursors = MySQLdb.cursors
    yield setup_db

@pytest.fixture
def patch_cursor_connection(monkeypatch, patch_cursor):
    def connect_to_db(*args, **kwargs):
        return patch_cursor, patch_cursor.cursor()

    from Database import connection
    connection.connect_to_db = connect_to_db
    yield patch_cursor

@pytest.mark.usefixtures("monkeypatch")
def test_userAppExists_dummy(patch_cursor_connection):
    from Database.user import userExists
    assert userExists('fakeemail@test.com') is None

...
```

Function to test is userExists which makes use of Database.connection.connect_to_db to retrieve connection and cursor and then closes the connection at the end.

Adding a try/except and new connection for dropping database is a workaround to bypass this.

Only problem is, that is not a target solution because doesn't allow to test something like this:

```
...
@pytest.mark.usefixtures("monkeypatch")
def test_userAppExists_dummy(patch_cursor_connection):
    from Database.user import userExists
    assert userExists('fakeemail@test.com') is None
    assert userExists('fakeemail2@test.com') is None
```
because in the first block `userExists` at the end connection is closed, so I can't use mysqlnoproc_client fixture to reconnect again (can we add this by default so we don't have to add a try/except block?)

**Comment by fizyk** [comment]
I'd encourage you to actually have your code that will be tested to connect on it's own, and treat the connection fixture as something that:

* set's up database state for the test
* is used to check the database state after the test (if something was changed as expected)

Right now the cause of the issue would be the patching part.

See here: https://github.com/fizyk/pyramid_fullauth/blob/main/tests/conftest.py#L34 I create the code-used connections (with the use of sqlalchemy here) even though I request the given connection fixture with open connection anyway.

**Comment by GabrieleCalarota** [comment]
> I'd encourage you to actually have your code that will be tested to connect on it's own, and treat the connection fixture as something that:
> 
> * set's up database state for the test
> * is used to check the database state after the test (if something was changed as expected)
> 
> Right now the cause of the issue would be the patching part.
> 
> See here: https://github.com/fizyk/pyramid_fullauth/blob/main/tests/conftest.py#L34 I create the code-used connections (with the use of sqlalchemy here) even though I request the given connection fixture with open connection anyway.

I understand the approach, I'll try this and I let you know if it suits my use case.

Thanks for the support and for the quick reply!
