### ISSUE TITLE
NameError: name 'mysql_db' is not defined

### ISSUE THREAD

**Issue by zx80** [ClearcodeHQ/pytest-mysql#343]
### What action do you want to perform

Running a tests on a mariadb backend.

### What are the results

The run fails while generating an error message.

### What are the expected results

That the run would hit the error and be able to generate a useful error message so that I could see it.
In `factories/client.py` around line 69:

```python
def _connect(connect_kwargs: dict, query_str: str) -> MySQLdb.Connection:
        """Apply given query to a  given MySQLdb connection."""
        mysql_conn: MySQLdb.Connection = MySQLdb.connect(**connect_kwargs)
        try:
            mysql_conn.query(query_str)
        except ProgrammingError as e:
            if "database exists" in str(e):
                raise DatabaseExists(
                    f"Database {mysql_db} already exists. There's some test "
                    f"configuration error. Either you start your own server "
                    f"with the database name used in tests, or you use two "
                    f"fixtures with the same database name on the same "
                    f"process fixture."
                ) from e
```

gets:   `NameError: name 'mysql_db' is not defined`

Indeed, the `mysql_db` variable does not seem to be defined anywhere in the function scope.

Another issue is that I the hint is not clear enough. I guess I'm probably in the *you use two fixtures with the same database name on the same process fixture*, but I do not understand where I could change the database name in a test... I thought that I replicated the doc examples so it should work...

**Comment by fizyk** [comment]
@zx80 the first error should be fixed on the main branch.

As for the issue you face... could you share your test code or similar test setup that fails?

I don't think we would be able to detect which fixtures have the same database name.

The client fixture factory, allows you to define your own name: https://github.com/ClearcodeHQ/pytest-mysql/blob/main/src/pytest_mysql/factories/client.py#L35
