### ISSUE TITLE
Unhelpful example...

### ISSUE THREAD

**Issue by zx80** [ClearcodeHQ/pytest-mysql#344]
### What action do you want to perform

Understand how the module works to run some tests. It seems that the only documentation is the README and the sources.

### What are the results

More efforts that should be necessary are needed to understand the stuff, basically you have to read the source. Example from the README:

```python
# assumes setting, these can be obtained from pytest-mysql config or mysql_proc
connection = f'mysql+mysqldb://root:@127.0.0.1:3307/tests?charset=utf8'
```

Great, I want to do that. The comment is unhelful, it should rather be specific by providing the code to do so.
Where is the doc about `mysql_proc`? Is there a nice method to get the connection string?
Well after some digging through `factories/process.py` and `executor.py`, the answer seems to be *no*.
I surmise that I can get user, host and port in the proc. Getting the database name and charset is still unclear.

Another point is that it is unclear whether it could work without resetting the user to getuser(), because
the default `root` is never going to work on any installation. If so, why not change the default?

Also there is a `mysql_noproc` fixture, which is not clearly advertised in the README which only tell about `mysql` and `mysql_proc`.

### What are the expected results

Having working self-contained examples from the simpler to the not so simple would help users not to spend so much time on the module to be able to use it.

**Comment by fizyk** [comment]
Okay, README needs to be updated with mysql_noproc to the list of default fixtures
And is the (Executor's) API documentation something you'd look for? 🤔
