### ISSUE TITLE
Support MariaDB

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-mysql#68]
### What action do you want to perform

Use pytest-mysql on Debian Stretch with stock `mysql-server` package, i.e. MariaDB 10.1.26.

### What are the results

Fails to start MySQL in `mysql_proc_fixture` with
```
2018-02-23  9:33:47 140272886743616 [ERROR] mysqld: unknown option '--initialize-insecure'
2018-02-23  9:33:47 140272886743616 [ERROR] Aborting
```
in the log.

### What are the expected results

Tests pass.

Before MariaDB support is added, we could detect it in #67 for a clearer error message.

**Comment by fizyk** [comment]
this just landed with tests on master
